"""
Testing, debugging, sanity checking 100m Veg in the FIS and Monte Carlo simulations.
DISCLAIMER: majority generated by AI
"""


import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats

from analysis.vegetation_fis_custom import calculate_vegetation_fis_custom



def test_1_identical_inputs(n_sims=1000):
    """
    Test 1: Use IDENTICAL inputs for 30m and 100m
    If sensitivity differs, there's definitely a bug
    """
    print("TEST 1: Identical Inputs")
    print("=" * 40)
    
    # Generate identical base inputs
    np.random.seed(42)  # For reproducibility
    base_input = np.random.normal(2.2, 0.4, 1)  # Same for both
    
    
    results = []
    
    for sim in range(n_sims):
        # Generate identical scale factors
        scale_30m = np.random.normal(1.0, 0.25)
        scale_100m = np.random.normal(1.0, 0.25)
        # scale_30m = 1.0
        # scale_100m = 1.0
        
        # Truncate to reasonable bounds
        scale_30m = np.clip(scale_30m, 0.5, 1.5)
        scale_100m = np.clip(scale_100m, 0.5, 1.5)
        
        feature_values = {
            1: {
                'iVeg_30EX': base_input,
                'iVeg100EX': base_input,
                'oVC': None # Placeholder, will be filled by Veg FIS
            }
        }
        
        # Simulate FIS with identical inputs but different scales
        calculate_vegetation_fis_custom(feature_values, 'iVeg_30EX', 'iVeg100EX', 'oVC',
                                        'scale', scale_30m,
                                        'scale', scale_100m)
        
        results.append({
            'sim': sim,
            '30m_scale': scale_30m,
            '100m_scale': scale_100m,
            'oVC': feature_values[1]['oVC']
        })
    
    test_data = pd.DataFrame(results)
    print(test_data)
    
    # Calculate sensitivities
    corr_30m = stats.pearsonr(test_data['30m_scale'], test_data['oVC'])[0]
    corr_100m = stats.pearsonr(test_data['100m_scale'], test_data['oVC'])[0]
    
    print(f"30m scale sensitivity: {corr_30m:.4f}")
    print(f"100m scale sensitivity: {corr_100m:.4f}")
    print(f"Ratio (100m/30m): {corr_100m/corr_30m:.4f}")
    
    if abs(corr_30m - corr_100m) > 0.05:
        print("⚠️  WARNING: Asymmetric sensitivity with identical inputs!")
        print("   This suggests a bug in the FIS implementation")
    else:
        print("✅ PASS: Similar sensitivity with identical inputs")
    
    return test_data

def test_2_swapped_inputs(n_sims=1000):
    """
    Test 2: Swap the input distributions
    Give 30m the 100m distribution and vice versa
    """
    print("\nTEST 2: Swapped Input Distributions")
    print("=" * 40)
    
    np.random.seed(43)
    
    # Generate swapped distributions
    input_30m_as_100m = np.random.normal(2.107, 0.3793, 400)  # 30m gets 100m dist
    input_100m_as_30m = np.random.normal(2.234, 0.5708, 400)  # 100m gets 30m dist
    
    results = []
    
    for sim in range(n_sims):
        scale_30m = np.random.normal(1.0, 0.75)
        scale_100m = np.random.normal(1.0, 0.75)
        
        scale_30m = np.clip(scale_30m, 0.1, 3.0)
        scale_100m = np.clip(scale_100m, 0.1, 3.0)
        
        feature_values = {
            sim: {
                'iVeg_30EX': input_30m_as_100m,
                'iVeg100EX': input_100m_as_30m,
                'oVC': None # Placeholder, will be filled by Veg FIS
            }
        }
        # Simulate FIS with identical inputs but different scales
        calculate_vegetation_fis_custom(feature_values, 'iVeg_30EX', 'iVeg100EX', 'oVC',
                                        'scale', scale_30m,
                                        'scale', scale_100m)
        
        results.append(feature_values)
    
    test_data = pd.DataFrame(results)
    
    corr_30m = stats.pearsonr(test_data['30m_scale'], test_data['oVC'])[0]
    corr_100m = stats.pearsonr(test_data['100m_scale'], test_data['oVC'])[0]
    
    print(f"30m scale sensitivity (with 100m distribution): {corr_30m:.4f}")
    print(f"100m scale sensitivity (with 30m distribution): {corr_100m:.4f}")
    print(f"Ratio (100m/30m): {corr_100m/corr_30m:.4f}")
    
    return test_data

def test_3_single_parameter_variation(n_sims=1000):
    """
    Test 3: Vary only ONE parameter at a time
    Hold all others constant
    """
    print("\nTEST 3: Single Parameter Variation")
    print("=" * 40)
    
    # Fixed inputs and base scales
    np.random.seed(44)
    fixed_30m = np.random.normal(2.234, 0.5708, 400)
    fixed_100m = np.random.normal(2.107, 0.3793, 400)
    
    # Test A: Vary only 30m scale
    results_30m = []
    for sim in range(n_sims):
        scale_30m = np.random.normal(1.0, 0.75)
        scale_100m = 1.0  # Fixed!
        
        scale_30m = np.clip(scale_30m, 0.1, 3.0)
        
        feature_values = {
            sim: {
                'iVeg_30EX': fixed_30m,
                'iVeg100EX': fixed_100m,
                'oVC': None # Placeholder, will be filled by Veg FIS
            }
        }
        # Simulate FIS with identical inputs but different scales
        calculate_vegetation_fis_custom(feature_values, 'iVeg_30EX', 'iVeg100EX', 'oVC',
                                        'scale', scale_30m,
                                        'scale', scale_100m)
        
        results_30m.append({
            'scale': scale_30m,
            'oVC': feature_values[sim]['oVC']
        })
    
    # Test B: Vary only 100m scale
    results_100m = []
    for sim in range(n_sims):
        scale_30m = 1.0  # Fixed!
        scale_100m = np.random.normal(1.0, 0.75)
        
        scale_100m = np.clip(scale_100m, 0.1, 3.0)
        
        feature_values = {
            sim: {
                'iVeg_30EX': fixed_30m,
                'iVeg100EX': fixed_100m,
                'oVC': None # Placeholder, will be filled by Veg FIS
            }
        }
        # Simulate FIS with identical inputs but different scales
        calculate_vegetation_fis_custom(feature_values, 'iVeg_30EX', 'iVeg100EX', 'oVC',
                                        'scale', scale_30m,
                                        'scale', scale_100m)
        
        results_100m.append({
            'scale': scale_100m,
            'oVC': feature_values[sim]['oVC']
        })
    
    data_30m = pd.DataFrame(results_30m)
    data_100m = pd.DataFrame(results_100m)
    
    corr_30m_only = stats.pearsonr(data_30m['scale'], data_30m['oVC'])[0]
    corr_100m_only = stats.pearsonr(data_100m['scale'], data_100m['oVC'])[0]
    
    print(f"30m scale sensitivity (100m fixed): {corr_30m_only:.4f}")
    print(f"100m scale sensitivity (30m fixed): {corr_100m_only:.4f}")
    print(f"Ratio (100m/30m): {corr_100m_only/corr_30m_only:.4f}")
    
    # Visualize
    plt.figure(figsize=(12, 4))
    
    plt.subplot(1, 2, 1)
    plt.scatter(data_30m['scale'], data_30m['oVC'], alpha=0.5)
    plt.xlabel('30m Scale Factor')
    plt.ylabel('oVC')
    plt.title(f'30m Only (r={corr_30m_only:.3f})')
    
    plt.subplot(1, 2, 2)
    plt.scatter(data_100m['scale'], data_100m['oVC'], alpha=0.5, color='orange')
    plt.xlabel('100m Scale Factor')
    plt.ylabel('oVC')
    plt.title(f'100m Only (r={corr_100m_only:.3f})')
    
    plt.tight_layout()
    plt.show()
    
    return data_30m, data_100m

def test_4_extreme_scales():
    """
    Test 4: Test with extreme scale factors to check for asymmetric behavior
    """
    print("\nTEST 4: Extreme Scale Factors")
    print("=" * 40)
    
    np.random.seed(45)
    test_input_30m = np.random.normal(2.234, 0.5708, 100)
    test_input_100m = np.random.normal(2.107, 0.3793, 100)
    
    extreme_scales = [0.5, 1.0, 1.5, 2.0]
    
    results = []
    
    for i, scale_30m in enumerate(extreme_scales):
        for scale_100m in extreme_scales:
            feature_values = {
                i+1: {
                    'iVeg_30EX': test_input_30m,
                    'iVeg100EX': test_input_100m,
                    'oVC': None # Placeholder, will be filled by Veg FIS
                }
            }
            # Simulate FIS with identical inputs but different scales
            calculate_vegetation_fis_custom(feature_values, 'iVeg_30EX', 'iVeg100EX', 'oVC',
                                            'scale', scale_30m,
                                            'scale', scale_100m)
            
            results.append({
                '30m_scale': scale_30m,
                '100m_scale': scale_100m,
                'mean_oVC': feature_values[i+1]['oVC'],
                'scenario': f"30m:{scale_30m}, 100m:{scale_100m}"
            })
    
    results_df = pd.DataFrame(results)
    
    # Create a pivot table to see the pattern
    pivot = results_df.pivot(index='30m_scale', columns='100m_scale', values='mean_oVC')
    
    print("Mean oVC by scale combination:")
    print(pivot.round(3))
    
    # Check if the pattern is symmetric
    print(f"\nSymmetry check:")
    for i, scale_a in enumerate(extreme_scales):
        for j, scale_b in enumerate(extreme_scales):
            if i < j:  # Only check upper triangle
                val_ab = pivot.loc[scale_a, scale_b]
                val_ba = pivot.loc[scale_b, scale_a]
                diff = abs(val_ab - val_ba)
                print(f"({scale_a},{scale_b}) vs ({scale_b},{scale_a}): {val_ab:.3f} vs {val_ba:.3f}, diff: {diff:.4f}")
    
    return results_df



# Run all tests
def run_all_debugging_tests():
    """Run complete debugging test suite"""
    
    print("FIS SENSITIVITY DEBUGGING TEST SUITE")
    print("=" * 60)
    
    # Test 1: Identical inputs
    test1_data = test_1_identical_inputs(100)
    
    # Test 2: Swapped distributions  
    # test2_data = test_2_swapped_inputs(100)
    
    # # Test 3: Single parameter variation
    # test3_30m, test3_100m = test_3_single_parameter_variation(100)
    
    # # Test 4: Extreme scales
    # test4_data = test_4_extreme_scales()
    
    print("\n" + "=" * 60)
    print("DEBUGGING SUMMARY:")
    print("If Test 1 shows asymmetry → Bug in FIS implementation")
    print("If Test 2 reverses the pattern → Issue is input distributions") 
    print("If Test 3 shows asymmetry → Bug in membership function scaling")
    print("If Test 4 shows asymmetry → Non-linear scaling artifacts")
    print("=" * 60)
    
    return {
        'test1': test1_data,
        # 'test2': test2_data, 
        # 'test3_30m': test3_30m,
        # 'test3_100m': test3_100m,
        # 'test4': test4_data
    }

# Usage:

# Replace simulate_vegetation_fis with your actual FIS function
# Then run:
results = run_all_debugging_tests()
print(results)
