"""
Performs additional analysis on BRAT Monte Carlo Simulation (a database generated by brat_montecarlo.py).
Generates 
Can print or save matplotlib plots.

INSTRUCTIONS:
    Run the script from the terminal, passing args (e.g. path to database) as defined

DISCLAIMER:
    AI and online resources were used to assist in writing these functions

Evan Hackstadt
August 2025
"""



#imports
import os
import sys
import argparse
import traceback
import sqlite3
import numpy as np
import pandas as pd
from scipy import stats
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score


def analyze(database, out_dir):
    """
    Master function called in main. Calls sub-functions for different analyses.
    :param database: path to a BRAT database (.gpkg)
    :param out_dir: optional path to a folder to save plots to
    """
    print("Analyzing database {}".format(os.path.basename(database)))
    if out_dir is not None:
        print("Output dir provided; saving plots to {}".format(out_dir))

    # > Call analysis functions. Can turn these on or off
    
    diagnositcs(database)
    
    for var in input_cols:
        var_distributions(database, out_dir, var, "Inputs")
    for var in adjustment_cols:
        var_distributions(database, out_dir, var, "Adjustments")

    for var in adjustment_cols:
        var_capacity_scatters(database, out_dir, var)
        # var_capacity_scatters_conditional(database, out_dir, var, std_tolerance=0.5)

    calculate_morris_effects(database, out_dir)
    
    corr_tornado_results = create_tornado_diagram(database, method='correlation', out_dir=out_dir)
    print("Most sensitive parameter:", corr_tornado_results['summary_table'].iloc[0]['Parameter'])
    print("Sensitivity value:", corr_tornado_results['summary_table'].iloc[0]['Sensitivity'])
    
    veg_hydro_sensitivity_comp(database, out_dir, corr_tornado_results)
    
    variance_decompisition(database, out_dir)
    
    # check_veg_input_corr(database)
    
    # OLD ANALYSIS.PY
    # capacity_scatter_plots(database, out_dir)
    # capacity_scatter_plots_zoomed(database, out_dir)
    # capacity_bar_plots(database, out_dir)
    
    print("Analysis complete.")


# USEFUL DICTIONARIES used by multiple functions

input_cols = ['iVeg_30EX', 'iVeg100EX', 'iHyd_SPLow', 'iHyd_SP2', 'iGeo_Slope']

adjustment_cols = ['Veg30_Scale', 'Veg100_Scale', 'SPLow_Scale', 'SPLow_Shift',
                    'SP2_Scale', 'SP2_Shift', 'Slope_Scale', 'Slope_Shift']

veg_adjustments = [col for col in adjustment_cols if 'Veg' in col]
hydro_adjustments = [col for col in adjustment_cols if 'SP' in col or 'Slope' in col]

adjustment_labels = {
    'Veg30_Scale': 'Scale Veg30 (30m Suitability)',
    'Veg100_Scale': 'Scale Veg100 (100m Suitability)', 
    'SPLow_Scale': 'Scale SPLow (Baseflow)',
    'SPLow_Shift': 'Shift SPLow (Baseflow)',
    'SP2_Scale': 'Scale SP2 (Peak Flow)',
    'SP2_Shift': 'Shift SP2 (Peak Flow)',
    'Slope_Scale': 'Scale Slope',
    'Slope_Shift': 'Shift Slope'
}


# Modular analysis functions

def diagnositcs(database):
    # Compare parameter ranges and output responses

    print("Parameter Ranges and Output Responses:")
    print("=" * 50)
    
    data = get_results_data(database)

    for param in adjustment_cols:
        param_range = data[param].max() - data[param].min()
        param_std = data[param].std()
        
        # Calculate output range when this parameter varies
        sorted_data = data.sort_values(param)
        bottom_10pct = sorted_data.head(int(len(data)*0.1))['AVG_oCC_EX'].mean()
        top_10pct = sorted_data.tail(int(len(data)*0.1))['AVG_oCC_EX'].mean()
        output_response = abs(top_10pct - bottom_10pct)
        
        # Standardized sensitivity calculation
        standardized_sens = output_response / param_range if param_range > 0 else 0
        
        print(f"{param}:")
        print(f"  Parameter range: {param_range:.4f} (std: {param_std:.4f})")
        print(f"  Output response: {output_response:.4f}")
        print(f"  Standardized sensitivity: {standardized_sens:.4f}")
        print()


def var_distributions(database, out_dir, var, table, num_bins=50, kde_switch=False):
    """
    Generate histograms of the distribution of relevant input variables. Options to filter.
    :param database: path to a BRAT database (.gpkg)
    :param out_dir: optional path to a folder to save plots to
    """
    
    var_data = select_var(database, var, table)

    # plot raw data
    sns.histplot(data=var_data, bins=num_bins, kde=kde_switch)
    plt.xlabel(var)
    plt.ylabel('Count')
    plt.title(f"Distribution of {var} in Siletz Watershed")
    print(f"...{num_bins}-bin histogram for {var} generated...")

    if out_dir is not None:
        print(f"...Saving plot to output dir...")
        out_file_path = os.path.join(out_dir, f"distribution-{var}.png")
        plt.savefig(out_file_path)
        plt.close()
    else:
        plt.show()


def create_tornado_diagram(database: str, output_col='AVG_oCC_EX', method='correlation', 
                         title=None, figsize=(10, 8), out_dir=None):
    """
    Create tornado diagram showing parameter sensitivity for Monte Carlo results.
    Claude AI was used to write much of this function.
    
    Parameters:
    -----------
    database: str
        Path to the Monte Carlo database
    output_col : str
        Name of output column (default: 'oCC_EX')
    method : str
        Sensitivity method: 'correlation', 'regression', or 'standardized'
    title : str
        Custom plot title
    figsize : tuple
        Figure size (width, height)
    save_path : str
        Path to save figure (optional)
    
    Returns:
    --------
    sensitivity_results : dict
        Dictionary with sensitivity metrics and statistics
    """
    
    results_data = get_results_data(database)
        
    # Calculate sensitivity metrics
    sensitivity_metrics = {}
    p_values = {}
    
    for param in adjustment_cols:
        if param not in results_data.columns:
            print(f"Warning: {param} not found in data")
            continue
            
        x = results_data[param].values
        y = results_data[output_col].values
        
        # Remove any NaN values
        mask = ~(np.isnan(x) | np.isnan(y))
        x_clean = x[mask]
        y_clean = y[mask]
        
        if len(x_clean) < 10:  # Need minimum data points
            print(f"Warning: Insufficient data for {param}")
            continue
        
        if method == 'correlation':
            # Pearson correlation coefficient
            corr_coef, p_val = stats.pearsonr(x_clean, y_clean)
            sensitivity_metrics[param] = corr_coef
            p_values[param] = p_val
            
        elif method == 'regression':
            # Standardized regression coefficient
            scaler_x = StandardScaler()
            scaler_y = StandardScaler()
            
            x_std = scaler_x.fit_transform(x_clean.reshape(-1, 1)).flatten()
            y_std = scaler_y.fit_transform(y_clean.reshape(-1, 1)).flatten()
            
            reg = LinearRegression()
            reg.fit(x_std.reshape(-1, 1), y_std)
            sensitivity_metrics[param] = reg.coef_[0]
            
            # Calculate p-value for regression coefficient
            from scipy.stats import t
            n = len(x_clean)
            y_pred = reg.predict(x_std.reshape(-1, 1))
            mse = np.mean((y_std - y_pred) ** 2)
            se = np.sqrt(mse / np.sum((x_std - np.mean(x_std)) ** 2))
            t_stat = reg.coef_[0] / se
            p_val = 2 * (1 - t.cdf(np.abs(t_stat), n - 2))
            p_values[param] = p_val
            
        elif method == 'standardized':
            # Standard deviation-based sensitivity (Morris-like)
            param_range = np.percentile(x_clean, 95) - np.percentile(x_clean, 5)
            output_range = np.percentile(y_clean, 95) - np.percentile(y_clean, 5)
            sensitivity_metrics[param] = output_range / param_range if param_range != 0 else 0
            
            # Use correlation p-value for significance
            _, p_val = stats.pearsonr(x_clean, y_clean)
            p_values[param] = p_val
    
    # Sort parameters by absolute sensitivity
    sorted_params = sorted(sensitivity_metrics.keys(), 
                          key=lambda x: abs(sensitivity_metrics[x]), reverse=False)
    
    # Prepare data for plotting
    param_names = [adjustment_labels[p] for p in sorted_params]
    sensitivities = [sensitivity_metrics[p] for p in sorted_params]
    p_vals = [p_values[p] for p in sorted_params]
    
    # Create tornado plot
    plt.figure(figsize=figsize)
    
    # Color bars by sign and significance
    colors = []
    for i, (sens, p_val) in enumerate(zip(sensitivities, p_vals)):
        if p_val < 0.05:  # Significant
            if sens > 0:
                colors.append('#d62728')  # Red for positive significant
            else:
                colors.append('#2ca02c')  # Green for negative significant
        else:  # Not significant
            if sens > 0:
                colors.append('#ff7f7f')  # Light red for positive non-significant
            else:
                colors.append('#7fbf7f')  # Light green for negative non-significant
    
    # Create horizontal bar chart
    y_pos = np.arange(len(param_names))
    bars = plt.barh(y_pos, sensitivities, color=colors, alpha=0.8, edgecolor='black', linewidth=0.5)
    
    # Customize plot
    plt.yticks(y_pos, param_names, fontsize=11)
    plt.xlabel(f'Sensitivity Index ({method.capitalize()})', fontsize=12, fontweight='bold')
    plt.ylabel('Model Parameters', fontsize=12, fontweight='bold')
    
    if title is None:
        if method == 'correlation':
            title = 'Parameter Sensitivity for Combined Capacity (oCC)\nPearson Correlation Coefficients'
        elif method == 'regression':
            title = 'Parameter Sensitivity for Combined Capacity (oCC)\nStandardized Regression Coefficients'
        else:
            title = 'Parameter Sensitivity for Combined Capacity (oCC)\nStandardized Sensitivity Index'
    
    plt.title(title, fontsize=14, fontweight='bold', pad=20)
    
    # Add vertical line at zero
    plt.axvline(x=0, color='black', linestyle='-', linewidth=0.8)
    
    # Add significance indicators
    for i, (bar, p_val) in enumerate(zip(bars, p_vals)):
        if p_val < 0.001:
            sig_text = '***'
        elif p_val < 0.01:
            sig_text = '**'
        elif p_val < 0.05:
            sig_text = '*'
        else:
            sig_text = 'ns'
        
        # Position text at end of bar
        x_pos = bar.get_width()
        if x_pos >= 0:
            plt.text(x_pos + 0.01 * max(sensitivities), i, sig_text, 
                    va='center', ha='left', fontsize=10, fontweight='bold')
        else:
            plt.text(x_pos - 0.01 * max(abs(np.array(sensitivities))), i, sig_text, 
                    va='center', ha='right', fontsize=10, fontweight='bold')
    
    # Add legend
    from matplotlib.patches import Patch
    legend_elements = [
        Patch(facecolor='#d62728', label='Positive Effect (p < 0.05)'),
        Patch(facecolor='#2ca02c', label='Negative Effect (p < 0.05)'),
        Patch(facecolor='#ff7f7f', label='Positive Effect (p ≥ 0.05)'),
        Patch(facecolor='#7fbf7f', label='Negative Effect (p ≥ 0.05)')
    ]
    plt.legend(handles=legend_elements, fontsize=10)
    
    # Add significance note
    plt.figtext(0.02, 0.02, '* p < 0.05, ** p < 0.01, *** p < 0.001, ns = not significant', 
                fontsize=9, style='italic')
    
    plt.tight_layout()
    plt.grid(axis='x', alpha=0.3)
    
    if out_dir is not None:
        print(f"...Saving tornado plot...")
        out_file_path = os.path.join(out_dir, f"tornado-{method}.png")
        plt.savefig(out_file_path, dpi=600)
        plt.close()
    else:
        plt.show()
    
    # Create summary table
    summary_df = pd.DataFrame({
        'Parameter': [adjustment_labels[p] for p in sorted_params],
        'Sensitivity': sensitivities,
        'P_value': p_vals,
        'Rank': range(1, len(sorted_params) + 1),
        'Significant': ['Yes' if p < 0.05 else 'No' for p in p_vals]
    })
    
    print("\nSensitivity Analysis Summary:")
    print("=" * 60)
    print(summary_df.to_string(index=False, float_format='%.4f'))
    
    # Return results for further analysis
    results = {
        'sensitivity_metrics': sensitivity_metrics,
        'p_values': p_values,
        'summary_table': summary_df,
        'method': method
    }
    
    return results


        # TODO — BROKEN - plotting is bugged

'''
def compare_sensitivity_methods(database, output_col='AVG_oCC_EX', figsize=(15, 6)):
    """
    Compare tornado diagrams using different sensitivity methods side by side.
    """
    methods = ['correlation', 'regression', 'standardized']
    method_titles = ['Pearson Correlation', 'Regression Coefficient', 'Range-Based Index']
    
    fig, axes = plt.subplots(1, 3, figsize=figsize, sharey=True)
    
    for i, (method, method_title) in enumerate(zip(methods, method_titles)):
        plt.sca(axes[i])
        results = create_tornado_diagram(database, output_col=output_col, 
                                       method=method, title=method_title,
                                       figsize=(5, 6))
        if i > 0:
            plt.ylabel('')  # Remove y-label for subsequent plots
    
    plt.tight_layout()
    plt.show()
    
    return None
'''


def var_capacity_scatters(database: str, out_dir: str, var: str, table: str = "ResultStats"):
    """
    Standard scatter plot of a variable against oCC_EX
    """
    var_data = select_var(database, var, table)
    cap_data = select_var(database, "AVG_oCC_EX", table)
    # seaborn scatter
    sns.regplot(x=var_data, y=cap_data, marker='.')
    plt.title(f"{var} Impact on Capacity")
    plt.xlabel(var)
    plt.ylabel("Mean oCC_EX for Input Reaches")
    # add r2 value
    r, p = stats.pearsonr(var_data, cap_data)
    ax = plt.gca()
    ax.text(.05, .8, 'r={:.2f}, p={:.2g}'.format(r, p),
            transform=ax.transAxes)
    
    if out_dir is not None:
        print(f"...Saving {var} scatter...")
        out_file_path = os.path.join(out_dir, f"{var}-scatter.png")
        plt.savefig(out_file_path)
        plt.close()
    else:
        plt.show()

  
def var_capacity_scatters_conditional(database: str, out_dir: str, var: str, std_tolerance=0.5):
    """
    Use standard deviation-based tolerance for each parameter type
    tolerance_std: how many standard deviations away from center
    """
    other_params = [col for col in adjustment_cols if col != var]
    
    # get data
    data = get_results_data(database)
    
    # Get stdev of all adjustment distributions
    stdevs = {}
    with sqlite3.connect(database) as conn:
        cur = conn.cursor()
        cur.execute("SELECT Adjustment, Parameters FROM AdjustmentDistributions")
        results = cur.fetchall()
        for row in results:
            params = row[1].split(", ")
            stdevs[row[0]] = float(params[1])  # stdev is second param for normals
    print(stdevs)
    
    # Define tolerance based on parameter type and its std dev
    param_tolerances = {}
    for param in other_params:
        if 'Scale' in param: # expect: mean=1.0, stdev=0.75
            center = 1.0
            tolerance = std_tolerance * stdevs[param]
        elif 'SPLow' in param and 'Shift' in param: # expect: mean=0, stdev=18.5
            center = 0.0
            tolerance = std_tolerance * stdevs[param]
        elif 'SP2' in param and 'Shift' in param: # expect: mean=0, stdev=200
            center = 0.0
            tolerance = std_tolerance * stdevs[param]
        elif 'Slope' in param and 'Shift' in param: # expect: mean=0, stdev=0.02
            center = 0.0
            tolerance = std_tolerance * stdevs[param]
        
        param_tolerances[param] = (center, tolerance)
    
    # Apply filters
    mask = True
    for param in other_params:
        center, tolerance = param_tolerances[param]
        mask = mask & (abs(data[param] - center) <= tolerance)
    
    filtered_data = data[mask]
    
    print(f"\nConditional Analysis for {var}:")
    print(f"Tolerance: {var} standard deviations")
    print(f"Retained {len(filtered_data)} simulations out of {len(data)} ({100*len(filtered_data)/len(data):.1f}%)")
    
    # Show tolerance values used
    print("Parameter tolerances used:")
    for param, (center, tol) in param_tolerances.items():
        print(f"  {param}: {center:.3f} ± {tol:.3f}")
    
    # seaborn scatter
    sns.regplot(x=filtered_data[var], y=filtered_data["AVG_oCC_EX"], marker='o')
    plt.title(f"{var} Impact on Capacity (Conditional Scatter)")
    plt.xlabel(var)
    plt.ylabel("Mean oCC_EX for Input Reaches")
    # add r2 value
    r, p = stats.pearsonr(filtered_data[var], filtered_data["AVG_oCC_EX"])
    ax = plt.gca()
    ax.text(.05, .8, 'r={:.2f}, p={:.2g}'.format(r, p),
            transform=ax.transAxes)
    
    if out_dir is not None:
        print(f"...Saving {var} conditional scatter...")
        out_file_path = os.path.join(out_dir, f"{var}-scatter-conditional.png")
        plt.savefig(out_file_path)
        plt.close()
    else:
        plt.show()


def calculate_morris_effects(database: str, out_dir: str, percentile=10):
    """
    Calculate Morris elementary effects - changes in output for unit changes in input
    This handles the confounding variable problem naturally
    """
    data = get_results_data(database)
    elementary_effects = {param: [] for param in adjustment_cols}
    
    for param in adjustment_cols:
        # Find pairs of simulations that differ mainly in this parameter
        param_values = data[param].values
        output_values = data["AVG_oCC_EX"].values
        
        # Sort by parameter value
        sort_idx = np.argsort(param_values)
        sorted_param = param_values[sort_idx]
        sorted_output = output_values[sort_idx]
        
        # Calculate finite differences
        for i in range(len(sorted_param) - 1):
            delta_param = sorted_param[i+1] - sorted_param[i]
            delta_output = sorted_output[i+1] - sorted_output[i]
            
            if abs(delta_param) > 1e-6:  # Avoid division by zero
                elementary_effect = delta_output / delta_param
                elementary_effects[param].append(elementary_effect)
    
    # Calculate statistics
    morris_stats = {}
    for param in adjustment_cols:
        effects = elementary_effects[param]
        if effects:
            morris_stats[param] = {
                'mean': np.mean(effects),
                'std': np.std(effects),
                'mean_abs': np.mean(np.abs(effects))
            }
    
    if out_dir is not None:
        print(f"...Printing Morris Effects to output dir...")
        out_file_path = os.path.join(out_dir, "morris-elementary-effects.txt")
        with open(out_file_path, "w") as file:
            for key, val in morris_stats.items():
                file.write(f"{key}\n")
                file.write(f"{val}\n")
                file.write("\n")
    else:
        print("==== Morris Elementary Effects: ====")
        for key, val in morris_stats.items():
            print(f"{key} = {val}")
    
    return morris_stats, elementary_effects


def veg_hydro_sensitivity_comp(database: str, out_dir: str, tornado_results):

    # Get tornado results and group them
    veg_sensitivity = np.mean([abs(tornado_results['sensitivity_metrics'][p]) for p in veg_adjustments])
    hydro_sensitivity = np.mean([abs(tornado_results['sensitivity_metrics'][p]) for p in hydro_adjustments])

    # Create comparison bar plot
    plt.figure(figsize=(6, 4))
    plt.bar(['Vegetation\nUncertainty', 'Hydrologic\nUncertainty'], 
            [veg_sensitivity, hydro_sensitivity], 
            color=['green', 'blue'], alpha=0.7)
    plt.ylabel('Mean Absolute Sensitivity')
    plt.title('Vegetation vs Hydrologic Parameter Importance')
    
    if out_dir is not None:
        print(f"...Saving plot to output dir...")
        out_file_path = os.path.join(out_dir, "veg-hydro-sensitivity-comparison.png")
        plt.savefig(out_file_path)
        plt.close()
    else:
        plt.show()


def variance_decompisition(database: str, out_dir: str):

    data = get_results_data(database)

    # Fit models to decompose variance
    X_veg = data[veg_adjustments].values
    X_hydro = data[hydro_adjustments].values  
    X_all = data[veg_adjustments + hydro_adjustments].values
    y = data['AVG_oCC_EX'].values

    # Calculate R² for different models
    r2_veg_only = LinearRegression().fit(X_veg, y).score(X_veg, y)
    r2_hydro_only = LinearRegression().fit(X_hydro, y).score(X_hydro, y)
    r2_full = LinearRegression().fit(X_all, y).score(X_all, y)

    # Create stacked bar showing variance explained
    plt.figure(figsize=(6, 4))
    plt.bar(['Vegetation\nOnly', 'Hydrology\nOnly', 'Combined\nModel'], 
            [r2_veg_only, r2_hydro_only, r2_full], alpha=0.7)
    plt.ylabel('Variance Explained (R²)')
    plt.title('Model Component Performance')
    plt.ylim(0, 1)
    
    if out_dir is not None:
        print(f"...Saving plot to output dir...")
        out_file_path = os.path.join(out_dir, "veg-hydro-variance-comparison.png")
        plt.savefig(out_file_path)
        plt.close()
    else:
        plt.show()

    
def check_veg_input_corr(database: str):
    cap_data = select_var(database, "oCC_EX", "Results")
    veg30_data = select_var(database, "iVeg_30EX", "Results")
    veg100_data = select_var(database, "iVeg100EX", "Results")
    
    # Check the actual relationship strength
    corr_30m = stats.pearsonr(veg30_data, cap_data)[0]
    corr_100m = stats.pearsonr(veg100_data, cap_data)[0]

    print(f"Direct correlation - 30m input to oVC: {corr_30m:.3f}")
    print(f"Direct correlation - 100m input to oVC: {corr_100m:.3f}")

    # Also check the variance in each input
    print(f"30m input variance: {np.var(veg30_data):.3f}")
    print(f"100m input variance: {np.var(veg100_data):.3f}")
    
    # Check if 100m has fundamentally stronger relationship with output
    
    plt.figure(figsize=(10, 4))

    plt.subplot(1, 2, 1)
    plt.scatter(veg30_data, cap_data, alpha=0.5)
    plt.xlabel('30m Vegetation Suitability')
    plt.ylabel('oVC')
    plt.title(f'30m vs oVC (r={corr_30m:.3f})')

    plt.subplot(1, 2, 2)  
    plt.scatter(veg100_data, cap_data, alpha=0.5, color='orange')
    plt.xlabel('100m Vegetation Suitability') 
    plt.ylabel('oVC')
    plt.title(f'100m vs oVC (r={corr_100m:.3f})')
    plt.show()



# OLD ANALYSIS.PY




def capacity_bar_plots(database, out_dir):
    """
    Generate bar charts for oCC_EX and categorical variables
    :param database: path to a BRAT database (.gpkg)
    :param out_dir: optional path to a folder to save plots to
    """

    # Variables of interest. Can easily be modified.
    x_vars = {
        # var name: ('description', '(optional) lookup table field', '(optional) lookup table name')
        'RiskID': ('Risk of conflict from damming', 'Name', 'DamRisks'),
    }

    # Get dam capacity outputs
    capacity_data = select_var(database, 'oCC_EX')

    # Get each variable, create scatter
    for var, info in x_vars.items():
        var_data = select_var(database, var)
        categories = list(set(var_data))      # unique categories

        # sort capacity data by category
        categorized_capacities = {}     # {category: [capacities list]}
        capacity_means = []
        for cat in categories:
            categorized_capacities[cat] = []
            for i in range(len(var_data)):      # var_data and capacity_data are parallel
                if var_data[i] == cat:
                    categorized_capacities[cat].append(capacity_data[i])
            # Find mean capacity in each category
            capacity_means.append(np.mean(categorized_capacities[cat]))
        
        # optionally change categories to names from an (ordered) lookup table
        if info[1] != '' and info[2] != '':
            conn = sqlite3.connect(database)
            curs = conn.cursor()
            curs.execute('SELECT {} FROM {}'.format(info[1], info[2]))
            result = curs.fetchall()
            categories = [row[0] for row in result]   # convert to ints from tuples
            curs.close()
         
        # generate a plot
        plt.bar(categories, capacity_means, width=0.7, tick_label=categories)
        plt.xlabel(var)
        plt.ylabel("Mean Dam Capacity (oCC_EX)")
        plt.title(f"{info[0]} vs. Dam Capacity")
        print(f"...Plot for {var} generated...")

        if out_dir is not None:
            print(f"...Saving plot to output dir...")
            out_file_path = os.path.join(out_dir, "bar-{}.png".format(var))
            plt.savefig(out_file_path)
            plt.close()
        else:
            plt.show()




def hydro_limitation(database, out_dir):
    """
    Analyze how hydro parameters (baseflow, peakflow, slope) limited the vegetative capacity.
    Reports # and % of reaches limited; generates colored scatters; generates cutoff-based histograms
    :param database: path to a BRAT database (.gpkg)
    :param out_dir: optional path to a folder to save plots to
    """

    # Hydrologic variables of interest (inputs into the Combined FIS)

    x_vars = {
        'iHyd_SPlow': 'Baseflow stream power (watts)',
        'iHyd_SP2': 'Peakflow stream power (watts)',
        'iGeo_Slope': 'Stream Slope'
    }
    categories = {  # var: [ {label, color, min, max}, ... ]
        'iHyd_SPlow': [
            {'label': 'Can build', 'color': 'b', 'min': 0, 'max': 160},
            {'label': 'Probably can build', 'color': 'y', 'min': 160, 'max': 185},
            {'label': 'Cannot build', 'color': 'r', 'min': 185}
        ],
        'iHyd_SP2': [
            {'label': 'Persists', 'color': 'b', 'min': 0, 'max': 1100},
            {'label': 'Occasional Breach', 'color': 'g', 'min': 1100, 'max': 1400},
            {'label': 'Occasional Blowout', 'color': 'y', 'min': 1400, 'max': 2200},
            {'label': 'Blowout', 'color': 'r', 'min': 2200}
        ],
        'iGeo_Slope': [
            {'label': 'Flat', 'color': 'c', 'min': 0, 'max': 0.0026},
            {'label': 'Can build', 'color': 'b', 'min': 0.0026, 'max': 0.135},
            {'label': 'Probably can build', 'color': 'g', 'min': 0.135, 'max': 0.20},
            {'label': 'Cannot build', 'color': 'r', 'min': 0.20, 'max': 1}
        ]
    }


    # Report what % of reaches were hydrologically limited
    print("HYDRO_LIMITATION REPORT:")
    oVC_EX = select_var(database, 'oVC_EX')
    oCC_EX = select_var(database, 'oCC_EX')

    num_diff = 0
    for i in range(len(oCC_EX)):
        if oCC_EX[i] != oVC_EX[i]:
            num_diff += 1
    perc_diff = round(100 * num_diff / len(oCC_EX), 2)
    print("> Of {} reaches, {} ({} percent) had their suitability limited by hydrology in Combined FIS".format(len(oCC_EX), num_diff, perc_diff))

    plt.pie([num_diff, len(oCC_EX) - num_diff], labels=['Limited by Hydrology', 'Not Limited by Hydrology'], autopct='%1.1f%%')
    if out_dir is not None:
        print(f"...Saving plot to output dir...")
        out_file_path = os.path.join(out_dir, "hydro-limit-pie.png")
        plt.savefig(out_file_path)
        plt.close()
    else:
        plt.show()

    # Generate color-coded oVC vs. oCC scatters to identify clusters & limiting factors
    print("Generating color-coded scatters:")
    for var, var_cat_list in categories.items():
        var_data = select_var(database, var)
        colors = []

        # for each value, replace it with the correct category label
        for i in range(len(var_data)):
            for cat in var_cat_list:
                label = cat['label']
                min = cat['min'] if 'min' in cat else None
                max = cat['max'] if 'max' in cat else None
                if (min is None or var_data[i] >= min) and (max is None or var_data[i] < max):
                    var_data[i] = label
                    colors.append(cat['color'])
                    break

        # generate a plot
        plt.scatter(oVC_EX, oCC_EX, s=0.75, marker='.', c=colors, alpha=0.5)
        for cat in var_cat_list:
            plt.scatter([], [], c=cat['color'], label=cat['label'])
        plt.legend(title=f'{var} Categories')
        plt.xlabel('oVC_EX (Veg FIS Capacity)')
        plt.ylabel("oCC_EX (Overall FIS Capacity)")
        plt.title(f"Veg Capacity vs. Overall Capacity - {var}")
        print(f"...Plot for {var} generated...")

        if out_dir is not None:
            print(f"...Saving plot to output dir...")
            out_file_path = os.path.join(out_dir, "hydro-limit-{}-coded.png".format(var))
            plt.savefig(out_file_path)
            plt.close()
        else:
            plt.show()
    

    
# HELPER functions

def get_results_data(database: str, table: str = "ResultStats"):
    """
    Return adjustments and outputs from a table (e.g. ResultStats) in monte carlo database as a DataFrame
    """
    results_cols = ['Veg30_Scale', 'Veg100_Scale', 'SPLow_Scale', 'SPLow_Shift', 
                    'SP2_Scale', 'SP2_Shift', 'Slope_Scale', 'Slope_Shift',
                    'AVG_oVC_EX', 'StDev_oVC_EX', 'AVG_oCC_EX', 'StDev_oVC_EX']
    
    with sqlite3.connect(database) as conn:
        cur = conn.cursor()
        cur.execute(f"SELECT {', '.join(results_cols)} FROM {table}")
        results = cur.fetchall()
        results_data = pd.DataFrame(results, columns=results_cols)

    return results_data

def select_var(database: str, var: str, table: str = "ReachAttributes", where: str = None):
    """
    Utility function to return column of values for a specified feature from a specified table
    :param database: path to a BRAT database (.gpkg)
    :param var: database name of the feature to be returned"""
    with sqlite3.connect(database) as conn:
        curs = conn.cursor()
        stmt = f"SELECT {var} FROM {table}"
        if where is not None:
            stmt += f" WHERE {where}"
        curs.execute(stmt)
        result = curs.fetchall()
        var_data = [row[0] for row in result]   # convert to ints from tuples

    print("Obtained {} {} values from database...".format(len(var_data), var))
    return var_data



def main():

    parser = argparse.ArgumentParser(
        description='Takes a BRAT database and performs additional analysis on the output variables in an attempt to identify any patterns.'
    )
    parser.add_argument('database', help='Path to at least one BRAT SQLite database (.gpkg). Add additional paths separated by spaces.', type=str)
    parser.add_argument('-o', '--output', help='(Optional) Path to an output directory where plots will be saved instead of displayed at runtime. If none provided, plots will not be saved.', type=str)
    args = parser.parse_args()
    print(args.database)

    try:
        analyze(args.database, args.output)

    except Exception as ex:
        traceback.print_exc(file=sys.stdout)
        sys.exit(1)

    sys.exit(0)


if __name__ == '__main__':
    main()
