"""
Performs additional analysis on BRAT Monte Carlo Simulation (a database generated by brat_montecarlo.py).
Generates histograms, scatters, tornado plot, 3D plots, computes morris elementary effects & sobol indices
Can print or save plots.

INSTRUCTIONS:
    Run the script from the terminal, passing args (e.g. path to database) as defined
    NOTE that most of the functions can't currently handle a database with multiple simulations (SimIDs).
        It is recommended to only pass in a database containing one Monte Carlo run.

DISCLAIMER:
    AI and online resources were used to assist in writing these functions

Evan Hackstadt
August 2025
"""



#imports
import os
import sys
import argparse
import traceback
import sqlite3
import numpy as np
import pandas as pd
from scipy import stats
import matplotlib.pyplot as plt
import seaborn as sns
from mpl_toolkits.mplot3d import Axes3D # Required for 3D plotting
from scipy.interpolate import griddata
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from SALib.analyze import sobol


def analyze(database, out_dir):
    """
    Master function called in main. Calls sub-functions for different analyses.
    :param database: path to a BRAT database (.gpkg)
    :param out_dir: optional path to a folder to save plots to
    """
    print("Analyzing database {}".format(os.path.basename(database)))
    if out_dir is not None:
        print("Output dir provided; saving plots to {}".format(out_dir))

    # > Call analysis functions. Can turn these on or off
    
    # diagnositcs(database)
    
    ''' Input and Adjustment Histograms '''
    # input_distributions(database, out_dir, compare_to_source=True)
    # adjustment_distributions(database, out_dir, compare_to_source=True)
    
    # for var in input_cols:
    #     var_distributions(database, out_dir, var, "Inputs")
    # for var in adjustment_cols:
    #     var_distributions(database, out_dir, var, "Adjustments")

    ''' Variable vs. Capacity Scatters '''
    # for var in adjustment_cols:
        # if "Veg" in var:
        #     var_capacity_scatters(database, out_dir, var, output="AVG_oVC_EX")
        #     var_capacity_scatters_conditional(database, out_dir, var, output="AVG_oVC_EX", std_tolerance=0.6)
        # var_capacity_scatters(database, out_dir, var)
        # var_capacity_scatters_conditional(database, out_dir, var, std_tolerance=0.6)

    ''' Isolate Adjustments; Sensitivity Analysis '''
    # calculate_morris_effects(database, out_dir)
    sobol_analysis(database, out_dir)
    # corr_tornado_results = create_tornado_diagram(database, method='correlation', out_dir=out_dir)
    # print("Most sensitive parameter:", corr_tornado_results['summary_table'].iloc[0]['Parameter'])
    # print("Sensitivity value:", corr_tornado_results['summary_table'].iloc[0]['Sensitivity'])
    # veg_hydro_sensitivity_comp(database, out_dir, corr_tornado_results)
    # variance_decompisition(database, out_dir)
    # check_veg_input_corr(database)
    
    ''' Combinations of Adjustments '''
    # for adj1 in adjustment_cols:
    #     for adj2 in adjustment_cols:
    #         if adj1 != adj2:
    #             results_3d_plot(database, out_dir, xvar=adj1, yvar=adj2)
    
    print("Analysis complete.")


# USEFUL DICTIONARIES used by multiple functions

input_cols = ['iVeg_30EX', 'iVeg100EX', 'iHyd_SPLow', 'iHyd_SP2', 'iGeo_Slope']

adjustment_cols = ['Veg30_Scale', 'Veg100_Scale', 'SPLow_Scale', 'SPLow_Shift',
                    'SP2_Scale', 'SP2_Shift', 'Slope_Scale', 'Slope_Shift']

veg_adjustments = [col for col in adjustment_cols if 'Veg' in col]
hydro_adjustments = [col for col in adjustment_cols if 'SP' in col or 'Slope' in col]

adjustment_labels = {
    'Veg30_Scale': 'Scale Veg30 (30m Suitability)',
    'Veg100_Scale': 'Scale Veg100 (100m Suitability)', 
    'SPLow_Scale': 'Scale SPLow (Baseflow)',
    'SPLow_Shift': 'Shift SPLow (Baseflow)',
    'SP2_Scale': 'Scale SP2 (Peak Flow)',
    'SP2_Shift': 'Shift SP2 (Peak Flow)',
    'Slope_Scale': 'Scale Slope',
    'Slope_Shift': 'Shift Slope'
}


# Modular analysis functions

def diagnositcs(database):
    # Compare parameter ranges and output responses

    print("Parameter Ranges and Output Responses:")
    print("=" * 50)
    
    data = get_results_data(database)

    for param in adjustment_cols:
        param_range = data[param].max() - data[param].min()
        param_std = data[param].std()
        
        # Calculate output range when this parameter varies
        sorted_data = data.sort_values(param)
        bottom_10pct = sorted_data.head(int(len(data)*0.1))['AVG_oCC_EX'].mean()
        top_10pct = sorted_data.tail(int(len(data)*0.1))['AVG_oCC_EX'].mean()
        output_response = abs(top_10pct - bottom_10pct)
        
        # Standardized sensitivity calculation
        standardized_sens = output_response / param_range if param_range > 0 else 0
        
        print(f"{param}:")
        print(f"  Parameter range: {param_range:.4f} (std: {param_std:.4f})")
        print(f"  Output response: {output_response:.4f}")
        print(f"  Standardized sensitivity: {standardized_sens:.4f}")
        print()


def input_distributions(database: str, out_dir: str, num_bins=25, compare_to_source: bool = False):
    
    fig = plt.figure(figsize=(12, 9))
    axs = fig.subplots(2, 3)
    index = 1
    
    for var in input_cols:
        # move to next axes and insert subplot
        plt.subplot(2, 3, index)
        cur_ax = plt.gca()
        var_ax = var_distribution(database, var, "Inputs", num_bins=num_bins, 
                                  stat='density', title=False, ylabel=False)
        cur_ax.axes = var_ax
        # format and prep vals
        cur_ax.set_ylabel(None)
        plt.yticks(fontsize=8)
        xlim = cur_ax.get_xlim()
        n = len(select_var(database, var, "Inputs"))
        
        # if compare_to_source, we need to plot the generating distribution
        if compare_to_source:
            dist_data = get_distribution_data(database, "InputDistributions")
            dist_name, p1, p2, p3, p4 = dist_data.loc[var]
            
            # Currently only handles these three distributions. if others used, will have to add.
            if dist_name == 'uniform':
                x = np.linspace(xlim[0], xlim[1], 1000)
                y = stats.uniform.pdf(x, loc=p1, scale=(p2-p1))
            elif dist_name == 'norm':
                x = np.linspace(xlim[0], xlim[1], 1000)
                y = stats.norm.pdf(x, loc=p1, scale=p2)
            elif dist_name == 'truncnorm':
                mu, sigma, left, right = p1, p2, p3, p4
                a, b = (left - mu) / sigma, (right - mu) / sigma
                x = np.linspace(left, right, num_bins)
                y = stats.truncnorm.pdf(x, a, b, loc=mu, scale=sigma)
            elif dist_name == 'expon':
                x = np.linspace(xlim[0], xlim[1], 1000)
                y = stats.expon.pdf(x, loc=p1, scale=p2)
            elif dist_name == 'pareto':
                x = np.linspace(xlim[0], xlim[1], 1000)
                y = stats.pareto.pdf(x, p1, loc=p2, scale=p3)
            if var == 'iGeo_Slope' and (dist_name == 'expon' or dist_name == 'pareto'):     # manual fix for slope hist
                cur_ax.set_xlim(0, 5)
                cur_ax.set_ylim(0, 3)
            plt.plot(x, y, 'r-', lw=3.5, alpha=0.6)
            
        index += 1
    
    # clear the last plot since we only use 5/6
    plt.subplot(2, 3, index)
    plt.gca().axis('off')
    
    # decorate figure
    fig.supylabel('Density')
    plt.figlegend(labels=['Generator Distribution'], loc='upper left', bbox_to_anchor=(0.65,0.3))
    
    if out_dir is not None:
        print(f"...Saving input distributions master figure...")
        out_file_path = os.path.join(out_dir, f"distribution-ALL-inputs.png")
        plt.savefig(out_file_path)
        plt.close()
    else:
        plt.show()
        
        
def adjustment_distributions(database: str, out_dir: str, num_bins=50, compare_to_source: bool = False):
    
    fig = plt.figure(figsize=(15, 9))
    axs = fig.subplots(2, 4)
    index = 1
    
    # reorder adjustment_cols to sort by adj type
    sorted_adjustment_cols = [adj for adj in adjustment_cols if "Scale" in adj]
    sorted_adjustment_cols += [adj for adj in adjustment_cols if "Shift" in adj]
    
    for var in sorted_adjustment_cols:
        # move to next axes and insert subplot
        plt.subplot(2, 4, index)
        cur_ax = plt.gca()
        var_ax = var_distribution(database, var, "Adjustments", num_bins=num_bins, 
                                  stat='density', title=False, ylabel=False)
        cur_ax.axes = var_ax
        # format and prep vals
        cur_ax.set_ylabel(None)
        plt.yticks(fontsize=8)
        xlim = cur_ax.get_xlim()
        n = len(select_var(database, var, "Adjustments"))
        
        # if compare_to_source, we need to plot the generating distribution
        if compare_to_source:
            dist_data = get_distribution_data(database, "AdjustmentDistributions")
            dist_name, p1, p2, p3, p4 = dist_data.loc[var]

            # Currently only handles these three distributions. if others used, will have to add.
            if dist_name == 'uniform':
                x = np.linspace(left, right, 1000)
                y = stats.uniform.pdf(x, loc=p1, scale=(p2-p1))
            elif dist_name == 'norm':
                x = np.linspace(xlim[0], xlim[1], 1000)
                y = stats.norm.pdf(x, loc=p1, scale=p2)
            elif dist_name == 'truncnorm':
                mu, sigma, left, right = p1, p2, p3, p4
                a, b = (left - mu) / sigma, (right - mu) / sigma
                x = np.linspace(left, right, 1000)
                y = stats.truncnorm.pdf(x, a, b, loc=mu, scale=sigma)
            plt.plot(x, y, 'r-', lw=3.5, alpha=0.6)
            
        index += 1
    
    fig.supylabel('Density')
    plt.figlegend(labels=[f'Generator Distribution'], loc='lower center')
    
    if out_dir is not None:
        print(f"...Saving adjustment distributions master figure...")
        out_file_path = os.path.join(out_dir, f"distribution-ALL-adjustments.png")
        plt.savefig(out_file_path)
        plt.close()
    else:
        plt.show()


def var_capacity_scatters(database: str, out_dir: str, var: str, 
                          table: str = "ResultStats", output: str = "AVG_oCC_EX"):
    """
    Standard scatter plot of a variable against oCC_EX
    """
    output_name = output.replace("AVG_", "")
    var_data = select_var(database, var, table)
    cap_data = select_var(database, output, table)
    
    # seaborn scatter
    sns.regplot(x=var_data, y=cap_data, marker='.')
    plt.xlabel(var)
    plt.ylabel(f"Mean {output_name} for Input Reaches")
    
    if "oVC" in output:
        plt.title(f"{var} Impact on VEG Capacity")
    else:
        plt.title(f"{var} Impact on Capacity")
    
    # add r2 value
    r, p = stats.pearsonr(var_data, cap_data)
    ax = plt.gca()
    ax.text(.05, .8, 'r={:.2f}, p={:.2g}'.format(r, p),
            transform=ax.transAxes)
    
    if out_dir is not None:
        print(f"...Saving {var} scatter...")
        out_file_path = os.path.join(out_dir, f"scatter-{var}-{output_name}.png")
        plt.savefig(out_file_path)
        plt.close()
    else:
        plt.show()

  
def var_capacity_scatters_conditional(database: str, out_dir: str, var: str,
                                      output: str = "AVG_oCC_EX", std_tolerance=0.5):
    """
    Use standard deviation-based tolerance for each parameter type
    tolerance_std: how many standard deviations away from center
    """
    other_params = [col for col in adjustment_cols if col != var]
    output_name = output.replace("AVG_", "")
    
    # get data
    data = get_results_data(database)
    
    # Get stdev of all adjustment distributions
    stdevs = {}
    with sqlite3.connect(database) as conn:
        cur = conn.cursor()
        cur.execute("SELECT Adjustment, Parameters FROM AdjustmentDistributions")
        results = cur.fetchall()
        for row in results:
            params = row[1].split(", ")
            stdevs[row[0]] = float(params[1])  # stdev is second param for normals
    print(stdevs)
    
    # Define tolerance based on parameter type and its std dev
    param_tolerances = {}
    for param in other_params:
        if 'Scale' in param: # expect: mean=1.0, stdev=0.75
            center = 1.0
            tolerance = std_tolerance * stdevs[param]
        elif 'SPLow' in param and 'Shift' in param: # expect: mean=0, stdev=18.5
            center = 0.0
            tolerance = std_tolerance * stdevs[param]
        elif 'SP2' in param and 'Shift' in param: # expect: mean=0, stdev=200
            center = 0.0
            tolerance = std_tolerance * stdevs[param]
        elif 'Slope' in param and 'Shift' in param: # expect: mean=0, stdev=0.02
            center = 0.0
            tolerance = std_tolerance * stdevs[param]
        
        param_tolerances[param] = (center, tolerance)
    
    # Apply filters
    mask = True
    for param in other_params:
        center, tolerance = param_tolerances[param]
        mask = mask & (abs(data[param] - center) <= tolerance)
    
    filtered_data = data[mask]
    
    print(f"\nConditional Analysis for {var}:")
    print(f"Tolerance: {var} standard deviations")
    print(f"Retained {len(filtered_data)} simulations out of {len(data)} ({100*len(filtered_data)/len(data):.1f}%)")
    
    # Show tolerance values used
    print("Parameter tolerances used:")
    for param, (center, tol) in param_tolerances.items():
        print(f"  {param}: {center:.3f} ± {tol:.3f}")
    
    # seaborn scatter
    sns.regplot(x=filtered_data[var], y=filtered_data[output], marker='o')
    plt.xlabel(var)
    plt.ylabel(f"Mean {output_name} for Input Reaches")
    
    if "oVC" in output:
        plt.title(f"{var} Impact on VEG Capacity (Conditional Scatter)")
    else:
        plt.title(f"{var} Impact on Capacity (Conditional Scatter)")
    
    # add r2 value
    r, p = stats.pearsonr(filtered_data[var], filtered_data[output])
    ax = plt.gca()
    ax.text(.05, .8, 'r={:.2f}, p={:.2g}'.format(r, p),
            transform=ax.transAxes)
    
    if out_dir is not None:
        print(f"...Saving {var} conditional scatter...")
        out_file_path = os.path.join(out_dir, f"scatter-conditional-{var}-{output_name}.png")
        plt.savefig(out_file_path)
        plt.close()
    else:
        plt.show()


def create_tornado_diagram(database: str, output_col='AVG_oCC_EX', method='correlation', 
                         title=None, figsize=(10, 8), out_dir=None):
    """
    Create tornado diagram showing parameter sensitivity for Monte Carlo results.
    Claude AI was used to write much of this function.
    
    Parameters:
    -----------
    database: str
        Path to the Monte Carlo database
    output_col : str
        Name of output column (default: 'oCC_EX')
    method : str
        Sensitivity method: 'correlation', 'regression', or 'standardized'
    title : str
        Custom plot title
    figsize : tuple
        Figure size (width, height)
    save_path : str
        Path to save figure (optional)
    
    Returns:
    --------
    sensitivity_results : dict
        Dictionary with sensitivity metrics and statistics
    """
    
    results_data = get_results_data(database)
        
    # Calculate sensitivity metrics
    sensitivity_metrics = {}
    p_values = {}
    
    for param in adjustment_cols:
        if param not in results_data.columns:
            print(f"Warning: {param} not found in data")
            continue
            
        x = results_data[param].values
        y = results_data[output_col].values
        
        # Remove any NaN values
        mask = ~(np.isnan(x) | np.isnan(y))
        x_clean = x[mask]
        y_clean = y[mask]
        
        if len(x_clean) < 10:  # Need minimum data points
            print(f"Warning: Insufficient data for {param}")
            continue
        
        if method == 'correlation':
            # Pearson correlation coefficient
            corr_coef, p_val = stats.pearsonr(x_clean, y_clean)
            sensitivity_metrics[param] = corr_coef
            p_values[param] = p_val
            
        elif method == 'regression':
            # Standardized regression coefficient
            scaler_x = StandardScaler()
            scaler_y = StandardScaler()
            
            x_std = scaler_x.fit_transform(x_clean.reshape(-1, 1)).flatten()
            y_std = scaler_y.fit_transform(y_clean.reshape(-1, 1)).flatten()
            
            reg = LinearRegression()
            reg.fit(x_std.reshape(-1, 1), y_std)
            sensitivity_metrics[param] = reg.coef_[0]
            
            # Calculate p-value for regression coefficient
            from scipy.stats import t
            n = len(x_clean)
            y_pred = reg.predict(x_std.reshape(-1, 1))
            mse = np.mean((y_std - y_pred) ** 2)
            se = np.sqrt(mse / np.sum((x_std - np.mean(x_std)) ** 2))
            t_stat = reg.coef_[0] / se
            p_val = 2 * (1 - t.cdf(np.abs(t_stat), n - 2))
            p_values[param] = p_val
            
        elif method == 'standardized':
            # Standard deviation-based sensitivity (Morris-like)
            param_range = np.percentile(x_clean, 95) - np.percentile(x_clean, 5)
            output_range = np.percentile(y_clean, 95) - np.percentile(y_clean, 5)
            sensitivity_metrics[param] = output_range / param_range if param_range != 0 else 0
            
            # Use correlation p-value for significance
            _, p_val = stats.pearsonr(x_clean, y_clean)
            p_values[param] = p_val
    
    # Sort parameters by absolute sensitivity
    sorted_params = sorted(sensitivity_metrics.keys(), 
                          key=lambda x: abs(sensitivity_metrics[x]), reverse=False)
    
    # Prepare data for plotting
    param_names = [adjustment_labels[p] for p in sorted_params]
    sensitivities = [sensitivity_metrics[p] for p in sorted_params]
    p_vals = [p_values[p] for p in sorted_params]
    
    # Create tornado plot
    plt.figure(figsize=figsize)
    
    # Color bars by sign and significance
    colors = []
    for i, (sens, p_val) in enumerate(zip(sensitivities, p_vals)):
        if p_val < 0.05:  # Significant
            if sens > 0:
                colors.append('#d62728')  # Red for positive significant
            else:
                colors.append('#2ca02c')  # Green for negative significant
        else:  # Not significant
            if sens > 0:
                colors.append('#ff7f7f')  # Light red for positive non-significant
            else:
                colors.append('#7fbf7f')  # Light green for negative non-significant
    
    # Create horizontal bar chart
    y_pos = np.arange(len(param_names))
    bars = plt.barh(y_pos, sensitivities, color=colors, alpha=0.8, edgecolor='black', linewidth=0.5)
    
    # Customize plot
    plt.yticks(y_pos, param_names, fontsize=11)
    plt.xlabel(f'Sensitivity Index ({method.capitalize()})', fontsize=12, fontweight='bold')
    plt.ylabel('Model Parameters', fontsize=12, fontweight='bold')
    
    if title is None:
        if method == 'correlation':
            title = 'Parameter Sensitivity for Combined Capacity (oCC)\nPearson Correlation Coefficients'
        elif method == 'regression':
            title = 'Parameter Sensitivity for Combined Capacity (oCC)\nStandardized Regression Coefficients'
        else:
            title = 'Parameter Sensitivity for Combined Capacity (oCC)\nStandardized Sensitivity Index'
    
    plt.title(title, fontsize=14, fontweight='bold', pad=20)
    
    # Add vertical line at zero
    plt.axvline(x=0, color='black', linestyle='-', linewidth=0.8)
    
    # Add significance indicators
    for i, (bar, p_val) in enumerate(zip(bars, p_vals)):
        if p_val < 0.001:
            sig_text = '***'
        elif p_val < 0.01:
            sig_text = '**'
        elif p_val < 0.05:
            sig_text = '*'
        else:
            sig_text = 'ns'
        
        # Position text at end of bar
        x_pos = bar.get_width()
        if x_pos >= 0:
            plt.text(x_pos + 0.01 * max(sensitivities), i, sig_text, 
                    va='center', ha='left', fontsize=10, fontweight='bold')
        else:
            plt.text(x_pos - 0.01 * max(abs(np.array(sensitivities))), i, sig_text, 
                    va='center', ha='right', fontsize=10, fontweight='bold')
    
    # Add legend
    from matplotlib.patches import Patch
    legend_elements = [
        Patch(facecolor='#d62728', label='Positive Effect (p < 0.05)'),
        Patch(facecolor='#2ca02c', label='Negative Effect (p < 0.05)'),
        Patch(facecolor='#ff7f7f', label='Positive Effect (p ≥ 0.05)'),
        Patch(facecolor='#7fbf7f', label='Negative Effect (p ≥ 0.05)')
    ]
    plt.legend(handles=legend_elements, fontsize=10)
    
    # Add significance note
    plt.figtext(0.02, 0.02, '* p < 0.05, ** p < 0.01, *** p < 0.001, ns = not significant', 
                fontsize=9, style='italic')
    
    plt.tight_layout()
    plt.grid(axis='x', alpha=0.3)
    
    if out_dir is not None:
        print(f"...Saving tornado plot...")
        out_file_path = os.path.join(out_dir, f"sensitivity-tornado-{method}.png")
        plt.savefig(out_file_path, dpi=600)
        plt.close()
    else:
        plt.show()
    
    # Create summary table
    summary_df = pd.DataFrame({
        'Parameter': [adjustment_labels[p] for p in sorted_params],
        'Sensitivity': sensitivities,
        'P_value': p_vals,
        'Rank': range(1, len(sorted_params) + 1),
        'Significant': ['Yes' if p < 0.05 else 'No' for p in p_vals]
    })
    
    print("\nSensitivity Analysis Summary:")
    print("=" * 60)
    print(summary_df.to_string(index=False, float_format='%.4f'))
    
    # Return results for further analysis
    results = {
        'sensitivity_metrics': sensitivity_metrics,
        'p_values': p_values,
        'summary_table': summary_df,
        'method': method
    }
    
    return results



def calculate_morris_effects(database: str, out_dir: str, percentile=10):
    """
    Calculate Morris elementary effects - changes in output for unit changes in input
    This handles the confounding variable problem naturally
    """
    data = get_results_data(database)
    elementary_effects = {param: [] for param in adjustment_cols}
    
    for param in adjustment_cols:
        # Find pairs of simulations that differ mainly in this parameter
        param_values = data[param].values
        output_values = data["AVG_oCC_EX"].values
        
        # Sort by parameter value
        sort_idx = np.argsort(param_values)
        sorted_param = param_values[sort_idx]
        sorted_output = output_values[sort_idx]
        
        # Calculate finite differences
        for i in range(len(sorted_param) - 1):
            delta_param = sorted_param[i+1] - sorted_param[i]
            delta_output = sorted_output[i+1] - sorted_output[i]
            
            if abs(delta_param) > 1e-6:  # Avoid division by zero
                elementary_effect = delta_output / delta_param
                elementary_effects[param].append(elementary_effect)
    
    # Calculate statistics
    morris_stats = {}
    for param in adjustment_cols:
        effects = elementary_effects[param]
        if effects:
            morris_stats[param] = {
                'mean': np.mean(effects),
                'std': np.std(effects),
                'mean_abs': np.mean(np.abs(effects))
            }
    
    plt_data = pd.DataFrame({
        'Adjustment': [adj for adj in morris_stats.keys()],
        'Absolute Mean': [stats['mean_abs'] for stats in morris_stats.values()],
        'Standard Deviation': [stats['std'] for stats in morris_stats.values()],
    })
    print(plt_data)
    
    # plot Morris mean vs. stddev
    plt.figure(figsize=(8,6))
    sns.scatterplot(data=plt_data, x='Absolute Mean', y='Standard Deviation',
                    s=100, alpha=0.75, hue='Adjustment', style='Adjustment')
    plt.xlabel("Absolute Mean of Elementary Effects")
    plt.ylabel("Standard Deviation of Elementary Effects")
    plt.legend()
    
    if out_dir is not None:
        print(f"...Printing Morris Effects to output dir...")
        png_file_path = os.path.join(out_dir, "morris-elementary-effects.png")
        txt_file_path = os.path.join(out_dir, "morris-elementary-effects.txt")
        plt.savefig(png_file_path, dpi=400)
        with open(txt_file_path, "w") as file:
            for key, val in morris_stats.items():
                file.write(f"{key}\n")
                file.write(f"{val}\n")
                file.write("\n")
    else:
        print("==== Morris Elementary Effects: ====")
        for key, val in morris_stats.items():
            print(f"{key} = {val}")
        plt.show()
    
    return morris_stats, elementary_effects


def sobol_analysis(database: str, out_dir: str):

    distdata = get_distribution_data(database, "AdjustmentDistributions")
    print(distdata)
    # all adjustment distributions are truncnorm, so params = mu,sigma,left,right

    # build problem and Y inputs
    problem = {
        'num_vars': len(adjustment_cols),
        'names': np.array([adj for adj in adjustment_cols]),
        'bounds': np.array(zip(distdata['Param3'], distdata['Param4']))
    }
    print(problem)
    all_data = get_results_data(database)
    data = all_data.drop(columns=['AVG_oVC_EX', 'StDev_oVC_EX', 'StDev_oVC_EX'])   # only use AVG_oCC_EX as output
    Y = np.array(data)
    
    if out_dir is not None:
        print(f"...Saving Sobol Indicies to output dir...")
        Si = sobol.analyze(problem, Y, calc_second_order=False, print_to_console=False)
        Si.plot()
        png_file_path = os.path.join(out_dir, "sobol-indices.png")
        plt.savefig(png_file_path, dpi=400)
        
        txt_file_path = os.path.join(out_dir, "sobol-indices.txt")
        with open(txt_file_path, "w") as file:
            for key, val in Si.items():
                file.write(f"{key}\n")
                file.write(f"{val}\n")
                file.write("\n")
    else:
        Si = sobol.analyze(problem, Y, calc_second_order=False, print_to_console=True)
        Si.plot()
        plt.show()
    
    return Si


def veg_hydro_sensitivity_comp(database: str, out_dir: str, tornado_results):

    # Get tornado results and group them
    veg_sensitivity = np.mean([abs(tornado_results['sensitivity_metrics'][p]) for p in veg_adjustments])
    hydro_sensitivity = np.mean([abs(tornado_results['sensitivity_metrics'][p]) for p in hydro_adjustments])

    # Create comparison bar plot
    plt.figure(figsize=(6, 4))
    plt.bar(['Vegetation\nUncertainty', 'Hydrologic\nUncertainty'], 
            [veg_sensitivity, hydro_sensitivity], 
            color=['green', 'blue'], alpha=0.7)
    plt.ylabel('Mean Absolute Sensitivity')
    plt.title('Vegetation vs Hydrologic Parameter Importance')
    
    if out_dir is not None:
        print(f"...Saving plot to output dir...")
        out_file_path = os.path.join(out_dir, "veg-hydro-sensitivity-comparison.png")
        plt.savefig(out_file_path)
        plt.close()
    else:
        plt.show()


def variance_decompisition(database: str, out_dir: str):

    data = get_results_data(database)

    # Fit models to decompose variance
    X_veg = data[veg_adjustments].values
    X_hydro = data[hydro_adjustments].values  
    X_all = data[veg_adjustments + hydro_adjustments].values
    y = data['AVG_oCC_EX'].values

    # Calculate R² for different models
    r2_veg_only = LinearRegression().fit(X_veg, y).score(X_veg, y)
    r2_hydro_only = LinearRegression().fit(X_hydro, y).score(X_hydro, y)
    r2_full = LinearRegression().fit(X_all, y).score(X_all, y)

    # Create stacked bar showing variance explained
    plt.figure(figsize=(6, 4))
    plt.bar(['Vegetation\nOnly', 'Hydrology\nOnly', 'Combined\nModel'], 
            [r2_veg_only, r2_hydro_only, r2_full], alpha=0.7)
    plt.ylabel('Variance Explained (R²)')
    plt.title('Model Component Performance')
    plt.ylim(0, 1)
    
    if out_dir is not None:
        print(f"...Saving plot to output dir...")
        out_file_path = os.path.join(out_dir, "veg-hydro-variance-comparison.png")
        plt.savefig(out_file_path)
        plt.close()
    else:
        plt.show()

    
def check_veg_input_corr(database: str):            # TODO - print/save these?
    cap_data = select_var(database, "oCC_EX", "Results")
    veg30_data = select_var(database, "iVeg_30EX", "Results")
    veg100_data = select_var(database, "iVeg100EX", "Results")
    
    # Check the actual relationship strength
    corr_30m = stats.pearsonr(veg30_data, cap_data)[0]
    corr_100m = stats.pearsonr(veg100_data, cap_data)[0]

    print(f"Direct correlation - 30m input to oVC: {corr_30m:.3f}")
    print(f"Direct correlation - 100m input to oVC: {corr_100m:.3f}")

    # Also check the variance in each input
    print(f"30m input variance: {np.var(veg30_data):.3f}")
    print(f"100m input variance: {np.var(veg100_data):.3f}")
    
    # Check if 100m has fundamentally stronger relationship with output
    
    plt.figure(figsize=(10, 4))

    plt.subplot(1, 2, 1)
    plt.scatter(veg30_data, cap_data, alpha=0.5)
    plt.xlabel('30m Vegetation Suitability')
    plt.ylabel('oVC')
    plt.title(f'30m vs oVC (r={corr_30m:.3f})')

    plt.subplot(1, 2, 2)  
    plt.scatter(veg100_data, cap_data, alpha=0.5, color='orange')
    plt.xlabel('100m Vegetation Suitability') 
    plt.ylabel('oVC')
    plt.title(f'100m vs oVC (r={corr_100m:.3f})')
    plt.show()


def results_3d_plot(database: str, out_dir: str, 
                    xvar: str = "Veg30_Scale", yvar: str = "Veg100_Scale", zvar: str = "AVG_oCC_EX"):
    # adapted from scikit-fuzzy docs
    # 3d plot where x1=Veg30_Scale, x2=Veg100_Scale, z=oCC_EX
    
    # raw data
    data = get_results_data(database)
    x = data[xvar].to_numpy()
    y = data[yvar].to_numpy()
    z = data[zvar].to_numpy()
    
    # create smooth grid
    xi = np.linspace(min(x), max(x), 20)
    yi = np.linspace(min(y), max(y), 20)
    xi, yi = np.meshgrid(xi, yi)
    zi = griddata((x, y), z, (xi, yi), method='linear')
    
    # plot
    fig = plt.figure()
    ax = fig.add_subplot(111, projection='3d')
    surf = ax.plot_surface(xi, yi, zi, cmap='viridis', edgecolor='none')
    
    # decorate
    fig.colorbar(surf, ax=ax, shrink=0.5, aspect=10, location='left', pad=0.025)
    ax.set_xlim(ax.get_xlim()[::-1])
    ax.set_xlabel(xvar)
    ax.set_ylabel(yvar)
    ax.set_zlabel(zvar)
    ax.set_title(f"Combined Effect of {xvar} and {yvar} on {zvar}")
    # ax.set(xticklabels=[], yticklabels=[], zticklabels=[])    # no axis labels
    fig.tight_layout()
    
    if out_dir is not None:
        print(f"...Saving 3D surface for {xvar} vs. {yvar} vs. {zvar}...")
        out_file_path = os.path.join(out_dir, f"3d-surface-{xvar}-{yvar}.png")
        plt.savefig(out_file_path, dpi=200)
        plt.close()
    else:
        plt.show()
    
    
    '''
    # We can simulate at higher resolution with full accuracy
    upsampled = np.linspace(-2, 2, 21)
    x, y = np.meshgrid(upsampled, upsampled)
    z = np.zeros_like(x)

    # Loop through the system 21*21 times to collect the control surface
    for i in range(21):
        for j in range(21):
            sim.input['error'] = x[i, j]
            sim.input['delta'] = y[i, j]
            sim.compute()
            z[i, j] = sim.output['output']

    # Plot the result in pretty 3D with alpha blending
    fig = plt.figure(figsize=(8, 8))
    ax = fig.add_subplot(111, projection='3d')

    surf = ax.plot_surface(x, y, z, rstride=1, cstride=1, cmap='viridis',
    linewidth=0.4, antialiased=True)

    cset = ax.contourf(x, y, z, zdir='z', offset=-2.5, cmap='viridis', alpha=0.5)
    cset = ax.contourf(x, y, z, zdir='x', offset=3, cmap='viridis', alpha=0.5)
    cset = ax.contourf(x, y, z, zdir='y', offset=3, cmap='viridis', alpha=0.5)

    ax.view_init(30, 200)
    '''


    
# HELPER functions

def var_distribution(database, var, table, stat='count', num_bins=50, kde_switch=False, title=True, ylabel=True, xlabel=True):
    """
    Generate histograms of the distribution of one variable (input or adjustment).
    :param database: path to a BRAT database (.gpkg)
    :param var: the variable (e.g. iGeo_Slope) to plot a histogram of
    :param stat: seaborn stat kwarg: choose count, frequency, probability, percent, or density
    :param num_bins: number of bins to plot the histogram with
    :param kde_switch: whether or not to plor the kernel density estimate curve on the histogram
    :param title: can disable adding a title to the plot
    :param out_dir: optional path to a folder to save plots to
    """
    
    var_data = select_var(database, var, table)

    # plot raw data
    ax = sns.histplot(data=var_data, bins=num_bins, stat=stat, kde=kde_switch)
    if xlabel:
        plt.xlabel(var)
    if ylabel:
        plt.ylabel(stat.capitalize())
    if title:
        plt.title(f"Distribution of {var} in Siletz Watershed")
        
    print(f"...{num_bins}-bin histogram for {var} generated...")
    return ax

def get_distribution_data(database: str, table: str = "AdjustmentDistributions"):
    """
    Helper function that selects, parses, and returns distributions for Adjustments or Inputs.
        Returns: DataFrame:
            x=Adj/Var   Distribution    Param1  Param2  Param3  Param4
        E.g. for a truncnorm, params:   mu     sigma    left    right
    """
    
    if "Adj" in table:
        xcol = "Adjustment"
        xlabel = adjustment_cols
    elif "Input" in table:
        xcol = "Var"
        xlabel = input_cols
    data = pd.DataFrame(index=xlabel, columns=['Distribution', 'Param1', 'Param2', 'Param3', 'Param4'])
    
    with sqlite3.connect(database) as conn:
        cur = conn.cursor()
        cur.execute(f"SELECT {xcol}, Distribution, Parameters FROM {table}")
        result = cur.fetchall()     # list of tuples, each tuple is a row
        for row in result:
            x, dist, paramstring = row
            paramstring = paramstring.replace("[", "")     # paramstring = [a, b, c, d]
            paramstring = paramstring.replace(" ", "")
            paramstring = paramstring.replace("]", "")
            params = [None, None, None, None]   # if no p3 or p4, will fill None
            for i, val in enumerate(paramstring.split(",")):
                params[i] = float(val)
            data.loc[x] = [dist] + params
    
    # print(data)
    return data

def get_results_data(database: str, table: str = "ResultStats"):
    """
    Helper function that returns adjustments and outputs
        from a table in monte carlo database (e.g. ResultStats) as a DataFrame
    """
    results_cols = ['Veg30_Scale', 'Veg100_Scale', 'SPLow_Scale', 'SPLow_Shift', 
                    'SP2_Scale', 'SP2_Shift', 'Slope_Scale', 'Slope_Shift',
                    'AVG_oVC_EX', 'StDev_oVC_EX', 'AVG_oCC_EX', 'StDev_oVC_EX']
    
    with sqlite3.connect(database) as conn:
        cur = conn.cursor()
        cur.execute(f"SELECT {', '.join(results_cols)} FROM {table}")
        results = cur.fetchall()
        results_data = pd.DataFrame(results, columns=results_cols)

    return results_data

def select_var(database: str, var: str, table: str = "ReachAttributes", where: str = None):
    """
    Helper function to return column of values for a specified feature from a specified table
    :param database: path to a BRAT database (.gpkg)
    :param var: database name of the feature to be returned"""
    with sqlite3.connect(database) as conn:
        curs = conn.cursor()
        stmt = f"SELECT {var} FROM {table}"
        if where is not None:
            stmt += f" WHERE {where}"
        curs.execute(stmt)
        result = curs.fetchall()
        var_data = [row[0] for row in result]   # convert to ints from tuples

    print("Obtained {} {} values from database...".format(len(var_data), var))
    return var_data



def main():

    parser = argparse.ArgumentParser(
        description='Takes a BRAT database and performs additional analysis on the output variables in an attempt to identify any patterns.'
    )
    parser.add_argument('database', help='Path to at least one BRAT SQLite database (.gpkg). Add additional paths separated by spaces.', type=str)
    parser.add_argument('-o', '--output', help='(Optional) Path to an output directory where plots will be saved instead of displayed at runtime. If none provided, plots will not be saved.', type=str)
    args = parser.parse_args()
    print(args.database)

    try:
        analyze(args.database, args.output)

    except Exception as ex:
        traceback.print_exc(file=sys.stdout)
        sys.exit(1)

    sys.exit(0)


if __name__ == '__main__':
    main()
